### ISSUE TITLE
about compensate command

### ISSUE THREAD

**Issue by yofizane** [yaqwsx/DrLCD#1]
hello,would u please tell me whats the meaning of  “amount of dimming” and  “black value for screen detection” in the compemsate command

**Comment by yaqwsx** [comment]
It is explained in this blog post: https://blog.honzamrazek.cz/2022/12/about-the-successful-quest-for-perfect-msla-printer-uv-backlight/

**Comment by yaqwsx** [comment]
The amount of dimming is the range of brightness (0-255) that is used to compensate for the bright spots. E.g. if you specify the amount to be 42, the most bright spot in the display will have brightness of 213 instead of 255.

The black value is a threshold of the sensor reading to detect areas outside of the LCD.

**Comment by yofizane** [comment]
thank u very much Jan Mrázek!
I am wondering if the TSL2561 sensor window is partially  outside the lcd screen,what will the  “cutoff” parameter do in that situation，   will the compensate still accurate?

**Comment by yaqwsx** [comment]
Given the size of the sensor vs. the size of brightness unevenness I think it is negligible. Nevertheless, there is still the option to crop the image manually.
